project:
  type: website
  output-dir: _site

execute:
  python: "../.pixi/envs/docs/bin/python3"

metadata-files:
  - _sidebar.yml

website:
  navbar:
    page_navigation: true
    favicon: "figures/pyfixest-logo.png"
    #page-footer:
    #  center: |
    #    Developed by [Alexander Fischer](https://github.com/py-econometrics) and [Styfen Sch√§r](https://github.com/styfenschaer)
    search: true
    right:
      - icon: github
        href: https://github.com/py-econometrics/pyfixest/
    left:
      - text: "PyFixest"
        file: pyfixest.md
      - text: "Quickstart"
        file: quickstart.qmd
      - text: "Function Reference"
        file: reference/index.qmd
      - text: "Changelog"
        file: changelog.qmd
      - text: "Contributing"
        file: contributing.qmd
      - text: "Acknowledgements"
        file: acknowledgements.md
      - text: "Sprint 2026"
        file: pyfixest-sprint.md
      - text: Learn more
        menu:
        - text: "Regression Tables and Summary Statistics"
          file: table-layout.qmd
        - text: "Hypothesis Testing and Marginal Effects"
          file: marginaleffects.qmd
        - text: "Difference-in-Differences Estimation"
          file: difference-in-differences.qmd
        - file: multiple_testing.ipynb
          text: "Multiple Testing Corrections"
        - file: regression_decomposition.ipynb
          text: "Regression Decomposition"
        - file: ssc.qmd
          text: "On Small Sample Corrections"
        - file: quantile-regression.qmd
          text: "Quantile Regression"
        #- text: "Compare fixest & PyFixest"
        #  file: compare-fixest-pyfixest.qmd
        - text: "Compare Stata & PyFixest"
          file: stata-2-pyfixest.qmd
        - text: "PyFixest on the GPU via CuPy"
          file: pyfixest-gpu-cupy.ipynb
        - text: "PyFixest on the GPU via JAX"
          file: pyfixest_gpu.ipynb
        - text: "Variance Reduction in AB Tests"
          file: panel_variance_reduction.ipynb
        - text: "Other Resources around PyFixest"
          file: resources.qmd
        - text: "Replicating 'The Effect' with PyFixest"
          file: replicating-the-effect.qmd
        - text: "Replicating 'The Mixtape' with PyFixest"
          file: mixtape.ipynb
        - text: "Replicating 'Causal Inference for the Brave and True' with PyFixest"
          file: brave_true.ipynb

quartodoc:
  package: pyfixest
  title: "PyFixest Function Reference"
  parser: numpy
  rewrite_all_pages: True
  sidebar: _sidebar.yml

  sections:
    - title: Estimation Functions
      desc: |
        User facing estimation functions
      contents:
        - estimation.api.feols.feols
        - estimation.api.fepois.fepois
        - estimation.api.feglm.feglm
        - estimation.api.quantreg.quantreg
        - did.estimation.did2s
        - did.estimation.lpdid
        - did.estimation.event_study
        - estimation.bonferroni
        - estimation.rwolf
    - title: Estimation Classes
      desc: |
        Details on Methods and Attributes
      contents:
        - estimation.feols_.Feols
        - estimation.fepois_.Fepois
        - estimation.feiv_.Feiv
        - estimation.feglm_.Feglm
        - estimation.felogit_.Felogit
        - estimation.feprobit_.Feprobit
        - estimation.fegaussian_.Fegaussian
        - estimation.feols_compressed_.FeolsCompressed
        - estimation.FixestMulti_.FixestMulti
        - estimation.quantreg.quantreg_.Quantreg
        #- did.did.DID
        #- did.did2s.DID2s
        #- did.lpdid.LPDID
        #- did.twfe.TWFE
    - title: Summarize and Visualize
      desc: |
        Post-Processing of Estimation Results
      contents:
        - did.visualize.panelview
        - report.summary
        - report.etable
        - report.dtable
        - report.coefplot
        - report.iplot
        - did.visualize.panelview
    - title: Misc / Utilities
      desc: |
        PyFixest internals and utilities
      contents:
        - estimation.demean
        - estimation.detect_singletons
        - estimation.model_matrix_fixest
