project:
  type: website
  output-dir: _site

execute:
  # point quarto to the correct python environment
  python: "/pyfixest/.pixi/envs/docs/Scripts/python.exe"

metadata-files:
  - _sidebar.yml

website:
  navbar:
    page_navigation: true
    favicon: "figures/pyfixest-logo.png"
    search: true
    right:
      - icon: github
        href: https://github.com/py-econometrics/pyfixest/
    left:
      - text: "PyFixest"
        file: pyfixest.md
      - text: "Getting Started"
        file: getting-started.qmd
      - text: "Tutorials"
        menu:
        - text: "All Tutorials"
          file: tutorials/index.qmd
        - text: "---"
        - text: "OLS with Fixed Effects"
          file: tutorials/ols-fixed-effects.qmd
        - text: "Standard Errors & Inference"
          file: tutorials/standard-errors.qmd
        - text: "Instrumental Variables"
          file: tutorials/instrumental-variables.qmd
        - text: "Poisson & GLMs"
          file: tutorials/poisson-glm.qmd
        - text: "Multiple Estimation"
          file: tutorials/multiple-estimation.qmd
        - text: "---"
        - text: "Regression Tables"
          file: tutorials/regression-tables.qmd
        - text: "Difference-in-Differences"
          file: tutorials/difference-in-differences.qmd
        - text: "Quantile Regression"
          file: tutorials/quantile-regression.qmd
      - text: "How-To Guides"
        menu:
        - text: "Hypothesis Testing & Marginal Effects"
          file: how-to/marginaleffects.qmd
        - text: "Multiple Testing Corrections"
          file: how-to/multiple_testing.ipynb
        - text: "Regression Decomposition"
          file: how-to/regression_decomposition.ipynb
        - text: "PyFixest on the GPU"
          file: how-to/pyfixest_gpu.ipynb
        - text: "---"
        - text: "Compare fixest & PyFixest"
          file: how-to/compare-fixest-pyfixest.qmd
        - text: "Translate Stata to PyFixest"
          file: how-to/stata-2-pyfixest.qmd
      - text: "Explanation"
        menu:
        - text: "On Small Sample Corrections"
          file: explanation/ssc.qmd
      - text: "Textbook Replications"
        menu:
        - text: "Replicating 'The Effect'"
          file: textbook-replications/replicating-the-effect.qmd
        - text: "Replicating 'The Mixtape'"
          file: textbook-replications/mixtape.ipynb
        - text: "Causal Inference for the Brave and True"
          file: textbook-replications/brave_true.ipynb
        - text: "Other Resources"
          file: textbook-replications/resources.qmd
      - text: "Function Reference"
        file: reference/index.qmd
      - text: "Changelog"
        file: changelog.qmd
      - text: "Contributing"
        file: contributing.qmd

quartodoc:
  package: pyfixest
  title: "PyFixest Function Reference"
  parser: numpy
  rewrite_all_pages: False
  sidebar: _sidebar.yml

  sections:
    - title: Estimation Functions
      desc: |
        User facing estimation functions
      contents:
        - estimation.estimation.feols
        - estimation.estimation.fepois
        - estimation.estimation.feglm
        - estimation.estimation.quantreg
        - did.estimation.did2s
        - did.estimation.lpdid
        - did.estimation.event_study
        - estimation.bonferroni
        - estimation.rwolf
    - title: Estimation Classes
      desc: |
        Details on Methods and Attributes
      contents:
        - estimation.feols_.Feols
        - estimation.fepois_.Fepois
        - estimation.feiv_.Feiv
        - estimation.feglm_.Feglm
        - estimation.felogit_.Felogit
        - estimation.feprobit_.Feprobit
        - estimation.fegaussian_.Fegaussian
        - estimation.feols_compressed_.FeolsCompressed
    - title: Summarize and Visualize
      desc: |
        Post-Processing of Estimation Results
      contents:
        - did.visualize.panelview
        - report.summary
        - report.etable
        - report.dtable
        - report.coefplot
        - report.iplot
        - did.visualize.panelview
    - title: Misc / Utilities
      desc: |
        PyFixest internals and utilities
      contents:
        - estimation.demean
        - estimation.detect_singletons
        - estimation.model_matrix_fixest
